---
name: Validate Specification

on:
  push:
    branches:
      - main
  pull_request:

permissions: read-all

jobs:
  validate-spec:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      - name: Validate specification
        run: |
          pipx install uv && \
          uvx openapi-spec-validator openapi.json